#pragma pack(push, 1)

typedef struct PropertiesTechnoClass
{
  PropertiesRadioClass r;
  int FlashFrames;
  int field_80;
  StageClass field_84;
  float Side;
  CargoClass Cargo;
  double Veterancy;
  double ArmorBonus;
  double FirePowerBonus;
  FrameTimerClass AnimationTimer;
  float field_CC;
  int field_D0;
  int field_D4;
  int field_D8;
  int field_DC;
  int OwningHouse;
  int Group;
  int FocusOn;
  HouseClass *Owner;
  int CloakState;
  ProgressTimerClass CloakProgress;
  FrameTimerClass CloakDelayTimer;
  int Target;
  int SuspendedTarCom;
  int PitchAngle;
  FrameTimerClass RearmTimer;
  int Ammo;
  int Value;
  float FireParticleSys;
  int SparkParticleSys;
  int NaturalParticleSys;
  int DamageParticleSys;
  int RailgunParticleSys;
  int WaveObject;
  int AngleRotatedSideways;
  int AngleRotatedForwards;
  int RockingSidewaysPerFrame;
  int RockingForwardsPerFrame;
  int InfiltratedInfType;
  StorageClass CreditLoad;
  DoorClass UnloadDoor;
  FacingClass BarrelFacing;
  FacingClass BodyFacing;
  FacingClass TurretFacing;
  int CurrentBurst;
  FrameTimerClass TargetLaserTimer;
  __int16 Seed;
  __int16 field_1F2;
  char field_1F4;
  char field_1F5;
  char Useless;
  char TickedOff;
  char Cloakable;
  char Primary;
  char Loaner;
  char Locked;
  char Recoil;
  char Tethered;
  char PlayerOwned;
  char PlayerAware;
  char AIAware;
  char field_201;
  char field_202;
  char field_203;
  char SightIncrease;
  char Recruitable;
  char AIRecruitable;
  char IsRadarTracked;
  char IsOnCarryall;
  char field_209;
  char IsPatroling;
  char field_20B;
  int ObjectNearToMe;
  int PlayerControlled;
  int field_214;
  int RandomSeed;
  char field_21C;
  char field_21D;
  char field_21E;
  char field_21F;
} PropertiesTechnoClass;

typedef struct vtTechnoClass vtTechnoClass;

typedef struct TechnoClass
{
  vtTechnoClass *vt;
  PropertiesTechnoClass p;
} TechnoClass;

struct vtTechnoClass
{
  vtRadioClass r;
  int TransmitMessage;
  int (__thiscall *Is_Allowed_To_Recloak)(int32_t);
  int field_224;
  int field_228;
  int field_22C;
  int (__thiscall *field_230)(int32_t);
  int field_234;
  int Is_Ready_To_Cloak;
  int Is_Ready_To_Uncloak;
  int field_240;
  int field_244;
  int (__thiscall *Is_Weapon_Equipped)(int32_t);
  int Tiberium_Load;
  int Weed_Load;
  int Pip_Count;
  int Refund_Amount;
  int field_25C;
  int Risk;
  int field_264;
  int field_268;
  int field_26C;
  int How_Many_Survivors;
  int TechnoClass_63A250;
  int Get_Collateral_Damage_Value;
  int Get_zAdjustment;
  int Get_zGradient;
  int Find_Docking_Bay;
  int field_288;
  int field_28C;
  int Desired_Load_Dir;
  int Fire_Direction;
  int field_298;
  int (__thiscall *Can_Player_Deploy)(int32_t);
  int (__thiscall *Player_Has_Control)(int32_t);
  int Get_Speed;
  int Rearm_Delay;
  int field_2AC;
  int Threat_Range;
  int field_2B4;
  int field_2B8;
  int Player_Sensor_Cell;
  int field_2C0;
  int (__thiscall *field_2C4)(int32_t);
  int field_2C8;
  int field_2CC;
  int Response_Move;
  int Response_Attack;
  int (__thiscall *Player_Assign_Mission)(int32_t, int32_t, int32_t, int32_t);
  int Target_Something_Nearby;
  int Stun;
  int In_Range;
  int Death_Announcement;
  int field_2EC;
  int Can_Fire;
  int Assign_Target;
  int Fire_At;
  int field_2FC;
  int Captured;
  int field_304;
  int field_308;
  int (__thiscall *What_Weapon_Should_I_Use)(int32_t, int32_t);
  int Has_Turret;
  int Renovate;
  int Cloaking_AI;
  int Rocking_AI;
  int field_320;
  int Remap_Table;
  int field_328;
  int field_32C;
  int Draw_Pips;
  int field_334;
  int Do_Uncloak;
  int Do_Cloak;
  int field_340;
  int Is_Ready_To_Random_Animate;
  int Random_Animate;
  int field_34C;
  int (__thiscall *Assign_Destination)(int32_t, int32_t, int32_t);
  int Enter_Idle_Mode;
  int field_358;
  int field_35C;
  int field_360;
  int (__thiscall *Tunnel_AI)(int32_t, int32_t);
};

#pragma pack(pop)
